name: chitchat
description: A Flutter group-oriented messaging app powered by Firebase as a backend.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.1
  flutter_dotenv: ^5.1.0
  firebase_auth: ^4.6.2
  firebase_messaging: ^14.6.2
  cloud_firestore: ^4.8.0
  image_picker: ^0.8.8
  firebase_storage: ^11.2.2
  flutter_native_splash: ^2.3.1
  google_fonts: ^4.0.4
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  android_12:
    color: "#ffffff"
    image: assets/images/splash.png

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/logo1.png
    - assets/images/logo2.png
    - assets/images/logo2-250x250.png
    - assets/images/logo2-removebg.png
    - assets/images/logo3.png
    - assets/images/default_profile_photo_1.png
    - assets/images/default_upload_photo_1.png
    - assets/images/default_upload_photo_2.png
    - assets/images/default_upload_photo_3.png
    - assets/images/splash.png